###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Mendel",
    "age": "81",
    "email": "mendel@gmail.com"
}

### 
GET http://localhost:9000/api/users HTTP/1.1

//despues del user poner el id con la lectura de arriba
###
GET http://localhost:9000/api/users/63353ac2b4dce1e152e3c0ee HTTP/1.1

//tambien le pasamos el id
###
PUT http://localhost:9000/api/users/63353e2f0ecfb2ce5e0e9b00 HTTP/1.1
Content-Type: application/json

{
    "name": "Manuel Mendel",
    "age": "81",
    "email": "manuelmendel@gmail.com"
}

//SE LE PASA EL ID
###
DELETE  http://localhost:9000/api/users/63353c47e581d12f7607758f HTTP/1.1
